### ISSUE TITLE
alternative nginx rewrite

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/cachebuster-plugin#3]
Moved from old repo, issue by @FlowFX.

Using the nginx rule from the Readme I get 404 errors when also enabling browser caching. This rule works for me, though:

```
location ~* (.+)\.(?:\d+)\.(js|css|png|jpg|jpeg|gif)$ {
    try_files $uri $1.$2;
}
```

I understand too little of nginx and regular expressions to say if this is a better solution or not.

**Comment by pedroborges** [comment]
Same here, the rule in the readme returns 404. Your solution works just fine.

Since Cachebuster caches js and css only, I changed the first line to:

    location ~* (.+)\.(?:\d+)\.(js|css)$ {
