### ISSUE TITLE
Idea: Option to add timestamp as querystring

### ISSUE THREAD

**Issue by dekodesign** [getkirby-v2/cachebuster-plugin#5]
This way, instead of resulting in a request for "stylesheet.1485564230.css", the plugin might instead request "stylesheet.css?1485564230". Should still keep things "fresh" and obviate the need for updating .htaccess to get cachebuster to work.

**Comment by neildaniels** [comment]
I wanted this behavior as well. I've added this to my fork and just opened a pull request: https://github.com/getkirby-plugins/cachebuster-plugin/pull/7
